# Generated by Django 2.0.2 on 2018-08-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('data_time', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.CharField(blank=True, max_length=250, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=50, null=True)),
                ('update_user', models.CharField(blank=True, max_length=50, null=True)),
                ('publish_user', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ispublic', models.IntegerField(blank=True, db_column='isPublic', null=True)),
                ('readhot', models.IntegerField()),
                ('downloads', models.IntegerField()),
                ('praise', models.IntegerField()),
                ('subscribesum', models.IntegerField()),
                ('geotype', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'datastore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstId', models.BigIntegerField(db_index=True)),
                ('secondId', models.BigIntegerField(db_index=True)),
                ('count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'histories',
                'managed': False,
            },
        ),
    ]
