# Generated by Django 2.0.2 on 2018-08-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstId', models.BigIntegerField(db_index=True)),
                ('secondId', models.BigIntegerField(db_index=True)),
                ('count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'histories',
                'managed': False,
            },
        ),
    ]
